### ISSUE TITLE
Add LspUnderline

### ISSUE THREAD

**Issue by jemag** [briones-gabriel/darcula-solid.nvim#1]
Really enjoying your theme, however it seems like the LspDiagnosticsUnderline*** are not defined. For example, with gruvbox theme, errors will show the underline like so:
![image](https://user-images.githubusercontent.com/7985687/119238595-651a6980-bb11-11eb-8a26-d5620c8bf7b9.png)
But no such underline with your themes are visible:
![image](https://user-images.githubusercontent.com/7985687/119238610-7d8a8400-bb11-11eb-8614-538e8cecced8.png)

**Comment by briones-gabriel** [comment]
Looks like I forgot to add them, I'll see what I can do.
Thanks for spotting the issue.

**Comment by briones-gabriel** [comment]
![image](https://user-images.githubusercontent.com/63462082/119241233-445f0d80-bb2b-11eb-9ce9-d9da8f0474f9.png)
What do you think, should the diagnostics change the color of the original object?
For example, functions are (originally) yellow, but when there is an error/information/warning their color would change to the diagnostics color (red, teal, yellow respectively).

**Comment by jemag** [comment]
Thanks for the PR adding underline!

Regarding the change of color of the original text, it is hard to say. On one side it does make errors "pop out" more, but may also remove some of the information conveyed by the original color.

In my case, I already use signs in the sign column + underline so I am not sure that I would need the additional visual indicator, but either way I think both options (changing the color or not) are fine. Probably a personal preference matter, feel free to implement the one that you prefer

**Comment by briones-gabriel** [comment]
I've updated the PR and gone "the gruvbox way" in this one.
![image](https://user-images.githubusercontent.com/63462082/119265360-cf3c1880-bbbc-11eb-9926-bab1f236d219.png)
As you say, both options are pretty good, but changing the color to match the Lsp diagnostic makes it confusing, so let's better go just with the underline for now.
