### ISSUE TITLE
Add a section on how to customise

### ISSUE THREAD

**Issue by rorystephenson** [briones-gabriel/darcula-solid.nvim#13]
I had some trouble customising this theme and the author of lush was very helpful in guiding me to [a working method](https://github.com/rktjmp/lush.nvim/issues/118).

So in case it can help someone else out, it works as follows (maybe this can be included in the README.md):

1. Create a `colors` directory if it doesn't exist at `~/.config/nvim/colors`.
2. Create a file for the modified theme: e.g `~/.config/nvim/colors/darcula-solid-custom`.
3. Set your modifications:
```lua
vim.opt.background = 'dark'
vim.g.colors_name = 'darcula-solid-custom'

local lush = require('lush')
local darcula_solid = require('lush_theme.darcula-solid')
local spec = lush.extends({darcula_solid}).with(function()
  -- Your modifications go here...
  -- Pallete copied from https://github.com/briones-gabriel/darcula-solid.nvim/blob/main/lua/lush_theme/darcula-solid.lua
  local yellow  = lush.hsl(37, 100, 71)

  return {
    Type { fg = yellow },
    Function { fg = darcula_solid.Normal.fg },
  }
end)

lush(spec)
```
4. In your config file (e.g. ~/.config/nvim/init.lua) set the theme to your custom one as follows:
```lua
vim.cmd("colorscheme darcula-solid-custom")
```

---

Thank you for the beautiful theme!

**Comment by briones-gabriel** [comment]
Hey @rorystephenson, thank you for your amazing idea. I will implement it right now!
