### ISSUE TITLE
Add support for listchars

### ISSUE THREAD

**Issue by lncrespo** [briones-gabriel/darcula-solid.nvim#4]
As of right now, listchars appear to be displayed in the same color as the background, therefore being invisible, also leading to the cursor becoming invisible while on a listchar.

You can see the issue really well while being in visual mode, the lighter gray is the selection while the cursor takes the foreground color of the text it's currently on. The listchars have the same foreground color as the background, rendering the cursor invisible in normal mode.
![image](https://user-images.githubusercontent.com/67927253/119251287-33071700-bba6-11eb-9bd2-234abd6fac12.png)

**Comment by lncrespo** [comment]
Even though it's easily changeable, it's pretty confusing as a default in my opinion, especially since the cursor becomes invisible in normal mode.

**Comment by briones-gabriel** [comment]
Thanks for the issue. I've created a pull request (#5) that solves the problem.
I would like to know your opinion on how they look in this new PR, compared with what they currently are in the main branch.
